# -*- coding: utf-8 -*-
"""Aula - Iteração com Dicionários.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgHlRxLBTOMzClyEVFDtm63VQd9IEWTj

Queremos saber quanto Carlos gastou no supermercado, e pra isso teremos que multiplicar os preços pelas quantidades
"""

preços = {'macarrão':4,'lasanha':5,'hamburguer':2}
quantidades={'macarrão':6,'lasanha':10,'hamburguer':10}

gasto= 0
for x in preços:
    gasto += (preços[x]*quantidades[x])
    print(gasto)

